const toast = document.querySelector('#toast');
const toastMessage = (message) => { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); };
const escapeHtml = (value) => { const element = document.createElement('span'); element.textContent = String(value); return element.innerHTML; };
const dateFormat = new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const incentiveMoney = (paise) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format((Number(paise) || 0) / 100);
const walletPanel = document.createElement('section');
walletPanel.className = 'agent-wallet-panel';
walletPanel.innerHTML = '<div><p class="eyebrow">AGENT INCENTIVES</p><h2>Your wallet</h2><strong id="agentWalletBalance">₹0.00</strong><p id="agentWalletNote">Complete vendor onboarding to earn incentives.</p></div><div><button class="button button-lime" id="agentWithdraw" type="button">Withdraw available balance <span>→</span></button><p id="agentPayoutHistory" class="wallet-history"></p></div><div id="agentCreditHistory" class="wallet-history"></div>';
document.querySelector('.metrics').after(walletPanel);
const payoutDialog = document.createElement('dialog');
payoutDialog.className = 'agent-payout-dialog';
payoutDialog.innerHTML = '<button type="button" class="close-agent-payout" aria-label="Close">×</button><p class="eyebrow">AGENT WALLET</p><h2>Verify and withdraw</h2><p>First withdrawal requires bank account verification. Your available incentive balance is requested in full.</p><form id="agentPayoutForm" novalidate><label>Account holder name <span class="required-marker">*</span><input id="agentPayoutHolder" required minlength="2" maxlength="120" autocomplete="name"/></label><label>Bank account number <span class="required-marker">*</span><input id="agentPayoutAccount" required inputmode="numeric" pattern="[0-9]{9,24}" minlength="9" maxlength="24" autocomplete="off"/></label><label>IFSC code <span class="required-marker">*</span><input id="agentPayoutIfsc" required pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" maxlength="11" autocapitalize="characters" autocomplete="off"/></label><p id="agentPayoutError" class="form-error" role="alert"></p><button class="button button-lime full" type="submit">Verify &amp; withdraw <span>→</span></button></form></dialog>';
document.body.append(payoutDialog);
let walletState = { balancePaise: 0, payoutAccount: null, credits: [], payouts: [] };
async function loadWallet() { const response = await fetch('/api/agent/wallet', { credentials: 'same-origin' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load your incentive wallet.'); walletState = data; document.querySelector('#agentWalletBalance').textContent = incentiveMoney(data.balancePaise); document.querySelector('#agentWalletNote').textContent = data.payoutAccount ? `Verified payout account ending ${data.payoutAccount.accountLast4}. Withdraw anytime.` : 'Verify your bank details once before your first withdrawal.'; document.querySelector('#agentWithdraw').disabled = !data.balancePaise; document.querySelector('#agentCreditHistory').innerHTML = data.credits.length ? `<strong>Recent incentives</strong>${data.credits.slice(0, 3).map((credit) => `<span>${escapeHtml(credit.vendorName)} · ${incentiveMoney(credit.amountPaise)}</span>`).join('')}` : '<span>No incentive credits yet.</span>'; document.querySelector('#agentPayoutHistory').textContent = data.payouts[0] ? `Latest withdrawal: ${incentiveMoney(data.payouts[0].amountPaise)} · ${data.payouts[0].status}` : ''; }
document.querySelector('#agentWithdraw').addEventListener('click', () => { if (walletState.balancePaise > 0) payoutDialog.showModal(); });
document.querySelector('#agentWithdraw').addEventListener('click', async (event) => { if (!walletState.payoutAccount || walletState.balancePaise <= 0) return; event.stopImmediatePropagation(); if (!window.confirm(`Withdraw ${incentiveMoney(walletState.balancePaise)} to your verified account ending ${walletState.payoutAccount.accountLast4}?`)) return; const button = event.currentTarget; button.disabled = true; try { const response = await fetch('/api/agent/wallet/payout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: '{}' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not request your withdrawal.'); toastMessage(data.message); await loadWallet(); } catch (error) { toastMessage(error.message); } finally { button.disabled = false; } }, true);
document.querySelector('.close-agent-payout').addEventListener('click', () => payoutDialog.close());
document.querySelector('#agentPayoutForm').addEventListener('submit', async (event) => { event.preventDefault(); const error = document.querySelector('#agentPayoutError'); error.textContent = ''; if (!event.target.checkValidity()) { error.textContent = 'Enter valid bank account details.'; return; } const button = event.target.querySelector('[type="submit"]'); button.disabled = true; try { const response = await fetch('/api/agent/wallet/payout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ accountHolder: document.querySelector('#agentPayoutHolder').value, accountNumber: document.querySelector('#agentPayoutAccount').value, ifscCode: document.querySelector('#agentPayoutIfsc').value }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not request your withdrawal.'); payoutDialog.close(); event.target.reset(); toastMessage(data.message); await loadWallet(); } catch (requestError) { error.textContent = requestError.message; } finally { button.disabled = false; } });
async function loadVendors() { const response = await fetch('/api/agent/vendors', { credentials: 'same-origin' }); if (response.status === 401 || response.status === 403) { window.location.href = 'index.html'; return; } const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load vendors.'); const accounts = data.accounts; document.querySelector('#vendorCount').textContent = accounts.length; document.querySelector('#accountRows').innerHTML = accounts.map((account) => `<tr><td><strong>${escapeHtml(`${account.firstName} ${account.lastName}`)}</strong><small>${escapeHtml(account.email)}</small></td><td><span class="role-chip Vendor">Vendor</span></td><td>${escapeHtml(account.phone)}</td><td>${dateFormat.format(new Date(account.createdAt * 1000))}</td></tr>`).join('') || '<tr><td colspan="4">No vendor accounts yet.</td></tr>'; }
async function loadSession() { const response = await fetch('/api/session', { credentials: 'same-origin' }); const data = await response.json(); if (!data.authenticated || data.account.role !== 'Agent') { window.location.href = 'index.html'; return false; } document.querySelector('#agentName').textContent = data.account.firstName; return true; }
document.querySelector('#logoutButton').addEventListener('click', async () => { await fetch('/api/signout', { method: 'POST', credentials: 'same-origin' }); window.location.href = 'index.html'; });
document.querySelector('#refreshAccounts').addEventListener('click', () => loadVendors().catch((error) => toastMessage(error.message)));
document.querySelector('#createVendorForm').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const error = document.querySelector('#createError'); error.textContent = ''; const fields = [...form.querySelectorAll('input')]; const invalid = fields.find((field) => !field.validity.valid); if (invalid) { error.textContent = 'Please complete every field with valid details.'; invalid.focus(); return; } if (document.querySelector('#password').value !== document.querySelector('#confirmPassword').value) { error.textContent = 'Passwords do not match.'; return; } const submit = form.querySelector('[type="submit"]'); submit.disabled = true; try { const response = await fetch('/api/agent/vendors', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ firstName: document.querySelector('#firstName').value, lastName: document.querySelector('#lastName').value, phone: document.querySelector('#phone').value, email: document.querySelector('#email').value, password: document.querySelector('#password').value, confirmPassword: document.querySelector('#confirmPassword').value }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not create vendor.'); form.reset(); toastMessage(result.message); await loadVendors(); } catch (requestError) { error.textContent = requestError.message; } finally { submit.disabled = false; } });
(async () => { if (await loadSession()) { loadVendors().catch((error) => toastMessage(error.message)); loadWallet().catch((error) => toastMessage(error.message)); } })();
