const toast = document.querySelector('#toast');
const toastMessage = (message) => { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); };
const escapeHtml = (value) => { const element = document.createElement('span'); element.textContent = String(value); return element.innerHTML; };
const dateFormat = new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
async function loadVendors() { const response = await fetch('/api/agent/vendors', { credentials: 'same-origin' }); if (response.status === 401 || response.status === 403) { window.location.href = 'index.html'; return; } const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load vendors.'); const accounts = data.accounts; document.querySelector('#vendorCount').textContent = accounts.length; document.querySelector('#accountRows').innerHTML = accounts.map((account) => `<tr><td><strong>${escapeHtml(`${account.firstName} ${account.lastName}`)}</strong><small>${escapeHtml(account.email)}</small></td><td><span class="role-chip Vendor">Vendor</span></td><td>${escapeHtml(account.phone)}</td><td>${dateFormat.format(new Date(account.createdAt * 1000))}</td></tr>`).join('') || '<tr><td colspan="4">No vendor accounts yet.</td></tr>'; }
async function loadSession() { const response = await fetch('/api/session', { credentials: 'same-origin' }); const data = await response.json(); if (!data.authenticated || data.account.role !== 'Agent') { window.location.href = 'index.html'; return false; } document.querySelector('#agentName').textContent = data.account.firstName; return true; }
document.querySelector('#logoutButton').addEventListener('click', async () => { await fetch('/api/signout', { method: 'POST', credentials: 'same-origin' }); window.location.href = 'index.html'; });
document.querySelector('#refreshAccounts').addEventListener('click', () => loadVendors().catch((error) => toastMessage(error.message)));
document.querySelector('#createVendorForm').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const error = document.querySelector('#createError'); error.textContent = ''; const fields = [...form.querySelectorAll('input')]; const invalid = fields.find((field) => !field.validity.valid); if (invalid) { error.textContent = 'Please complete every field with valid details.'; invalid.focus(); return; } if (document.querySelector('#password').value !== document.querySelector('#confirmPassword').value) { error.textContent = 'Passwords do not match.'; return; } const submit = form.querySelector('[type="submit"]'); submit.disabled = true; try { const response = await fetch('/api/agent/vendors', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ firstName: document.querySelector('#firstName').value, lastName: document.querySelector('#lastName').value, phone: document.querySelector('#phone').value, email: document.querySelector('#email').value, password: document.querySelector('#password').value, confirmPassword: document.querySelector('#confirmPassword').value }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not create vendor.'); form.reset(); toastMessage(result.message); await loadVendors(); } catch (requestError) { error.textContent = requestError.message; } finally { submit.disabled = false; } });
(async () => { if (await loadSession()) loadVendors().catch((error) => toastMessage(error.message)); })();
