const products = [
  { name: 'Moss ceramic set', type: 'Home / Table', price: 68, tag: 'NEW' },
  { name: 'Arc table light', type: 'Home / Lighting', price: 124, tag: 'BESTSELLER' },
  { name: 'Solace lounge chair', type: 'Home / Furniture', price: 460, tag: '' },
  { name: 'Form side table', type: 'Home / Furniture', price: 220, tag: 'LIMITED' }
];
const cart = [];
const mediaNavigationLink = document.createElement('a');
mediaNavigationLink.href = 'media.html';
mediaNavigationLink.textContent = 'Shagram';
document.querySelector('.site-header nav')?.append(mediaNavigationLink);
const jobsNavigationLink = document.createElement('a');
jobsNavigationLink.href = 'jobs.html';
jobsNavigationLink.textContent = 'Job offers';
document.querySelector('.site-header nav')?.append(jobsNavigationLink);
const ridesNavigationLink = document.createElement('a');
ridesNavigationLink.href = 'cab-booking.html';
ridesNavigationLink.textContent = 'Cab & Auto';
document.querySelector('.site-header nav')?.append(ridesNavigationLink);
const productGrid = document.querySelector('#productGrid');
const cartItems = document.querySelector('#cartItems');
const cartCount = document.querySelector('#cartCount');
const cartTotal = document.querySelector('#cartTotal');
const panel = document.querySelector('#cartPanel');
const overlay = document.querySelector('#overlay');
const toast = document.querySelector('#toast');

function escapeHtml(value) {
  const node = document.createElement('span');
  node.textContent = String(value);
  return node.innerHTML;
}
function money(amount, currency = 'USD') { return new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(amount); }
let productQuery = '';
function renderProducts() {
  const matchingProducts = products.map((product, index) => ({ product, index })).filter(({ product }) => `${product.name} ${product.type || ''} ${product.category || ''} ${product.productType || ''} ${product.keywords || ''}`.toLocaleLowerCase().includes(productQuery));
  productGrid.innerHTML = matchingProducts.map(({ product: p, index: i }) => { const media = p.mediaUrl ? (p.mediaUrl.endsWith('.mp4') || p.mediaUrl.endsWith('.webm') ? `<video class="customer-product-media" src="${escapeHtml(p.mediaUrl)}" muted playsinline controls></video>` : `<img class="customer-product-media" src="${escapeHtml(p.mediaUrl)}" alt="${escapeHtml(p.name)}"/>`) : ''; return `<article class="product"${p.id ? ` data-product-id="${Number(p.id)}"` : ''}>${media ? `<div class="product-image has-media">${media}</div>` : '<div class="product-image"></div>'}${p.tag ? `<span class="product-tag">${escapeHtml(p.tag)}</span>` : ''}<button class="add-product" data-index="${i}" aria-label="Add ${escapeHtml(p.name)} to bag">+</button><div class="product-info"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.type)}</small></div><span>${money(p.price, p.currency)}</span></div>${p.specifications ? `<p class="product-specifications">${escapeHtml(p.specifications)}</p>` : ''}</article>`; }).join('') || '<p class="product-search-empty">No products match that search. Try a name, category, type, or keyword.</p>';
}
const baseRenderProducts = renderProducts;
renderProducts = () => { baseRenderProducts(); document.querySelectorAll('#productGrid .product').forEach((card) => { const index = Number(card.querySelector('.add-product')?.dataset.index); const product = products[index]; if (!product) return; const productKey = product.id ? `id-${Number(product.id)}` : String(index); const detailUrl = `product-details.html?product=${encodeURIComponent(productKey)}`; card.dataset.productDetailsUrl = detailUrl; card.insertAdjacentHTML('beforeend', `<a class="product-details-link" href="${detailUrl}">View details <span>→</span></a>`); if (!product.customerActions) return; const actions = product.customerActions.map((action) => action === 'Buy' ? `<button class="customer-product-action" data-customer-action="buy" data-index="${index}">Buy</button>` : action === 'Book' ? `<button class="customer-product-action" data-customer-action="book" data-index="${index}">Book service</button>` : action === 'Callback' ? `<button class="customer-product-action" data-customer-action="callback" data-index="${index}">Request callback</button>` : `<a class="customer-product-action" href="tel:${escapeHtml(product.vendorPhone || '')}">Call for details</a>`).join(''); card.insertAdjacentHTML('beforeend', `<div class="customer-product-actions">${actions}</div>`); }); };
function renderCart() {
  cartCount.textContent = cart.length;
  if (!cart.length) { cartItems.innerHTML = '<p class="empty-cart">Your bag is ready when you are.</p>'; cartTotal.textContent = '$0.00'; return; }
  cartItems.innerHTML = cart.map((item, index) => `<div class="cart-line"><span>${escapeHtml(item.name)}</span><strong>${money(item.price, item.currency)}</strong><button data-remove="${index}" aria-label="Remove ${escapeHtml(item.name)}">Remove</button></div>`).join('');
  const currencies = new Set(cart.map((item) => item.currency || 'USD'));
  cartTotal.textContent = currencies.size === 1 ? money(cart.reduce((sum, item) => sum + item.price, 0), cart[0].currency) : 'Separate checkout required';
}
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); }
function openCart() { panel.classList.add('open'); overlay.classList.add('visible'); }
function closeCart() { panel.classList.remove('open'); overlay.classList.remove('visible'); }
const productSearch = document.createElement('form'); productSearch.className = 'home-product-search'; productSearch.setAttribute('role', 'search'); productSearch.innerHTML = '<button class="compact-location" type="button" id="useCurrentLocation" aria-label="Use current location" title="Use current location"><span aria-hidden="true">⌖</span><b>Location</b><small id="locationWeather">Select location</small></button><button class="home-search-symbol" type="button" aria-label="Open product search" title="Search products"><span aria-hidden="true"></span></button><label><input id="homeProductSearch" type="search" aria-label="Search products" placeholder="Search by name, category, type, or keyword" autocomplete="off"/></label>';
document.querySelector('.site-header')?.after(productSearch);
const bloodRequestButton = document.createElement('button'); bloodRequestButton.type = 'button'; bloodRequestButton.className = 'blood-request-icon'; bloodRequestButton.setAttribute('aria-label', 'Blood Requests'); bloodRequestButton.title = 'Blood Requests'; bloodRequestButton.innerHTML = '<span aria-hidden="true">♥</span>'; productSearch.querySelector('.compact-location').after(bloodRequestButton);
const bloodDialog = document.createElement('dialog'); bloodDialog.className = 'blood-request-dialog'; bloodDialog.innerHTML = '<button type="button" class="blood-close" aria-label="Close Blood Requests">×</button><p class="eyebrow">BLOOD SUPPORT</p><h2>Blood Requests</h2><p class="blood-note">Your exact location is used only to find eligible donors within 5 km.</p><form id="bloodPreferenceForm"><fieldset><legend>Are you a blood donor?</legend><label><input type="radio" name="donorStatus" value="Yes" required/> Yes</label><label><input type="radio" name="donorStatus" value="No"/> No</label><label><input type="radio" name="donorStatus" value="Decide later"/> Decide later</label></fieldset><button type="submit" class="blood-secondary">Save donor preference</button></form><hr/><form id="bloodRequestForm"><h3>Raise a Blood Request</h3><label>Blood group<select id="bloodGroup" required><option value="">Select</option><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option><option>O+</option><option>O-</option></select></label><label>Number of units<input id="bloodUnits" type="number" min="1" max="20" required/></label><label>Hospital details<textarea id="bloodHospital" minlength="3" maxlength="500" required></textarea></label><label>Reason for request<textarea id="bloodReason" minlength="3" maxlength="500" required></textarea></label><label>Contact details<input id="bloodContact" minlength="7" maxlength="200" required/></label><button type="submit" class="button button-lime full">Notify nearby donors <span>→</span></button></form><section class="blood-notifications" hidden><h3>Nearby Blood Requests</h3><div></div></section><p class="form-error" role="alert"></p></dialog>'; document.body.append(bloodDialog);
let bloodCoordinates = null;
function requestBloodLocation() { return new Promise((resolve, reject) => { if (!navigator.geolocation) return reject(new Error('Location is unavailable in this browser.')); navigator.geolocation.getCurrentPosition(({ coords }) => { bloodCoordinates = { latitude: coords.latitude, longitude: coords.longitude }; fetch('/api/blood/location', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(bloodCoordinates) }).catch(() => {}); resolve(bloodCoordinates); }, () => reject(new Error('Allow location access to use Blood Requests.')), { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); }); }
async function loadBloodNotifications() { const response = await fetch('/api/blood/notifications', { credentials: 'same-origin' }); if (!response.ok) return; const data = await response.json(); const section = bloodDialog.querySelector('.blood-notifications'); const list = section.querySelector('div'); section.hidden = !data.eligible; if (!data.eligible) return; list.innerHTML = data.requests.map((item) => `<article><b>${escapeHtml(item.bloodGroup)} · ${item.units} unit${item.units > 1 ? 's' : ''}</b><small>${escapeHtml(item.reason)} · ${item.radiusKm} km${item.escalated ? ' expanded radius' : ''}</small>${item.interested === true ? '<em>Details unlocked</em>' : `<button data-blood-interest="${item.id}" data-answer="yes">Interested</button><button data-blood-interest="${item.id}" data-answer="no">Not interested</button>`}</article>`).join('') || '<small>No nearby open requests.</small>'; }
bloodRequestButton.addEventListener('click', async () => { bloodDialog.querySelector('.form-error').textContent = ''; bloodDialog.showModal(); try { await requestBloodLocation(); await loadBloodNotifications(); } catch (error) { bloodDialog.querySelector('.form-error').textContent = error.message; } }); bloodDialog.querySelector('.blood-close').addEventListener('click', () => bloodDialog.close());
bloodDialog.querySelector('#bloodPreferenceForm').addEventListener('submit', async (event) => { event.preventDefault(); const status = new FormData(event.target).get('donorStatus'); const response = await fetch('/api/blood/preference', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ donorStatus: status }) }); const data = await response.json(); if (!response.ok) return bloodDialog.querySelector('.form-error').textContent = data.error || 'Could not save preference.'; showToast(data.message); await requestBloodLocation(); await loadBloodNotifications(); });
bloodDialog.querySelector('#bloodRequestForm').addEventListener('submit', async (event) => { event.preventDefault(); try { const coords = bloodCoordinates || await requestBloodLocation(); const response = await fetch('/api/blood/requests', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ bloodGroup: document.querySelector('#bloodGroup').value, units: Number(document.querySelector('#bloodUnits').value), hospitalDetails: document.querySelector('#bloodHospital').value, reason: document.querySelector('#bloodReason').value, contactDetails: document.querySelector('#bloodContact').value, ...coords }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not raise request.'); event.target.reset(); showToast(`${data.message} ${data.notified} donor${data.notified === 1 ? '' : 's'} nearby.`); } catch (error) { bloodDialog.querySelector('.form-error').textContent = error.message; } });
bloodDialog.querySelector('.blood-notifications').addEventListener('click', async (event) => { const button = event.target.closest('[data-blood-interest]'); if (!button) return; const response = await fetch('/api/blood/interest', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId: Number(button.dataset.bloodInterest), interested: button.dataset.answer === 'yes' }) }); const data = await response.json(); if (!response.ok) return bloodDialog.querySelector('.form-error').textContent = data.error || 'Could not save response.'; if (data.details) window.alert(`Request details\nBlood group: ${data.details.bloodGroup}\nUnits: ${data.details.units}\nHospital: ${data.details.hospitalDetails}\nReason: ${data.details.reason}\nContact: ${data.details.contactDetails}`); await loadBloodNotifications(); });
productSearch.querySelector('.home-search-symbol').addEventListener('click', () => { const searchLabel = productSearch.querySelector('label'); searchLabel.prepend(productSearch.querySelector('.home-search-symbol')); productSearch.classList.add('is-open'); document.querySelector('#homeProductSearch').focus(); });
productSearch.addEventListener('submit', (event) => { event.preventDefault(); productQuery = document.querySelector('#homeProductSearch').value.trim().toLocaleLowerCase(); renderProducts(); document.querySelector('#productGrid').scrollIntoView({ behavior: 'smooth', block: 'start' }); });
document.querySelector('#homeProductSearch').addEventListener('input', (event) => { productQuery = event.target.value.trim().toLocaleLowerCase(); renderProducts(); });
document.querySelector('#useCurrentLocation').addEventListener('click', () => { const button = document.querySelector('#useCurrentLocation'); const label = button.querySelector('b'); const weatherLabel = button.querySelector('small'); if (!navigator.geolocation) { label.textContent = 'Unavailable'; return; } label.textContent = 'Locating…'; weatherLabel.textContent = 'Loading weather'; navigator.geolocation.getCurrentPosition(async ({ coords }) => { const latitude = encodeURIComponent(coords.latitude); const longitude = encodeURIComponent(coords.longitude); try { const [placeResponse, weatherResponse] = await Promise.all([fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}&zoom=10`), fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code`)]); const place = await placeResponse.json(); const weather = await weatherResponse.json(); const address = place.address || {}; label.textContent = address.city || address.town || address.village || address.county || 'Current location'; const conditions = { 0: 'Sunny', 1: 'Mostly sunny', 2: 'Partly cloudy', 3: 'Cloudy', 45: 'Foggy', 51: 'Drizzle', 61: 'Rainy', 71: 'Snowy', 80: 'Showers', 95: 'Thunderstorms' }; weatherLabel.textContent = weather.current ? `${Math.round(weather.current.temperature_2m)}°C · ${conditions[weather.current.weather_code] || 'Current weather'}` : 'Weather unavailable'; } catch (_) { label.textContent = 'Current location'; weatherLabel.textContent = 'Weather unavailable'; } }, () => { label.textContent = 'Location'; weatherLabel.textContent = 'Permission needed'; }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); });
const marketTicker = document.createElement('div'); marketTicker.id = 'marketTicker'; marketTicker.className = 'market-ticker'; marketTicker.hidden = true; productSearch.after(marketTicker);
async function loadMarketTicker() {
  try {
    const [marketResponse, metalResponse, indexResponse] = await Promise.all([
      fetch('/api/market-rates', { credentials: 'same-origin' }),
      fetch('/api/metal-rates', { credentials: 'same-origin', cache: 'no-store' }),
      fetch('/api/index-rates', { credentials: 'same-origin', cache: 'no-store' }),
    ]);
    const rates = await marketResponse.json();
    const metals = metalResponse.ok ? await metalResponse.json() : null;
    const indices = indexResponse.ok ? await indexResponse.json() : null;
    const format = (value, decimals = 2) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: decimals, minimumFractionDigits: decimals }).format(Number(value));
    const pieces = [];
    const addPiece = (tag, label, value, tone = '', trend = '') => pieces.push({ tag, label, value, tone, trend });
    const indexPiece = (index) => {
      if (!index?.label || !Number.isFinite(Number(index.value))) return;
      const arrow = index.trend === 'up' ? '▲' : index.trend === 'down' ? '▼' : '●';
      const sign = Number(index.changePercent) > 0 ? '+' : '';
      const trendClass = index.trend === 'up' ? 'up' : index.trend === 'down' ? 'down' : 'flat';
      addPiece(index.exchange, index.label, format(index.value, 2), index.exchange === 'BSE' ? 'bse' : 'nse', { text: `${arrow} ${sign}${format(Math.abs(Number(index.changePercent) || 0), 2)}%`, className: trendClass });
    };
    if (indices?.sensex || indices?.nifty50) {
      indexPiece(indices.sensex);
      indexPiece(indices.nifty50);
    } else if (rates.sensex !== '') addPiece('BSE', 'SENSEX', format(rates.sensex, 2), 'bse');
    if (metals?.gold22k && metals?.gold24k && metals?.silver) {
      addPiece('22K', 'GOLD', `₹${format(metals.gold22k)}/g`, 'gold22');
      addPiece('24K', 'GOLD', `₹${format(metals.gold24k)}/g`, 'gold24');
      addPiece('', 'SILVER', `₹${format(metals.silver)}/g`);
    } else {
      if (rates.gold22k !== '') addPiece('22K', 'GOLD', `₹${format(rates.gold22k)}/g`, 'gold22');
      if (rates.gold24k !== '') addPiece('24K', 'GOLD', `₹${format(rates.gold24k)}/g`, 'gold24');
      if (rates.silver !== '') addPiece('', 'SILVER', `₹${format(rates.silver)}/g`);
    }
    if (!pieces.length) return;
    const indexStamp = indices?.updatedAt ? `NSE / BSE reference: ${indices.updatedAt}` : '';
    const metalStamp = metals?.updatedAt ? `IBJA reference: ${metals.updatedAt}` : '';
    const title = [indexStamp, metalStamp].filter(Boolean).join(' • ') || 'Indicative market rates';
    const itemMarkup = pieces.map((item) => `<span class="market-item${item.tone ? ` tone-${item.tone}` : ''}">${item.tag ? `<b class="market-tag">${item.tag}</b>` : ''}<b class="market-label">${item.label}</b><strong class="market-value">${item.value}</strong>${item.trend ? `<em class="market-trend ${item.trend.className}">${item.trend.text}</em>` : ''}</span>`).join('');
    marketTicker.innerHTML = `<div title="${title}">${itemMarkup}<span class="market-copy" aria-hidden="true">${itemMarkup}</span></div>`;
    marketTicker.hidden = false;
  } catch (_) { /* The home page remains usable if a market feed is unavailable. */ }
}
loadMarketTicker(); window.setInterval(loadMarketTicker, 300000);
renderProducts(); renderCart();
async function loadVendorProductsForCustomers() { const response = await fetch('/api/products', { credentials: 'same-origin' }); const data = await response.json(); if (!response.ok || !Array.isArray(data.products) || !data.products.length) return; const listed = data.products.map((product) => ({ id: product.id, name: product.name, type: [product.category, product.productType, product.vendorName].filter(Boolean).join(' · '), category: product.category || '', productType: product.productType || '', keywords: product.keywords || '', specifications: product.specifications || '', price: product.costPaise / 100, currency: 'INR', tag: 'VENDOR', mediaUrl: product.media?.[0] || '', customerActions: product.customerActions || ['Buy'], vendorPhone: product.vendorPhone || '' })); products.push(...listed); renderProducts(); }
loadVendorProductsForCustomers().catch(() => { /* The public storefront remains available without the API. */ });

productGrid.addEventListener('click', (event) => { const card = event.target.closest('.product[data-product-details-url]'); const detailsLink = event.target.closest('.product-details-link'); if (detailsLink || (card && !event.target.closest('button,a,video'))) { const url = detailsLink?.href || card.dataset.productDetailsUrl; if (!signedInAccount) { event.preventDefault(); promptProductAccess(url); return; } if (!detailsLink) window.location.href = url; return; } const button = event.target.closest('[data-index]'); if (!button) return; if (!signedInAccount) return promptProductAccess(card?.dataset.productDetailsUrl || 'product-details.html'); const product = products[Number(button.dataset.index)]; if (button.dataset.customerAction === 'book') { showToast(`Booking request started for ${product.name}.`); return; } if (button.dataset.customerAction === 'callback') { const preferred = window.prompt(`Preferred callback date and time for ${product.name} (for example: 20 Sep, 3:30 PM)`); if (preferred?.trim()) showToast(`Callback requested for ${preferred.trim()}. The Vendor will contact you.`); return; } cart.push(product); renderCart(); showToast(`${product.name} added to your bag`); });
cartItems.addEventListener('click', (event) => { const button = event.target.closest('[data-remove]'); if (!button) return; cart.splice(Number(button.dataset.remove), 1); renderCart(); });
document.querySelector('#cartButton').addEventListener('click', openCart); document.querySelector('#closeCart').addEventListener('click', closeCart); overlay.addEventListener('click', closeCart);
document.querySelector('#checkoutButton').addEventListener('click', () => { if (!cart.length) return showToast('Add something to your bag first.'); showToast('Secure checkout would redirect to your payment provider.'); });
document.querySelector('.book-now').addEventListener('click', () => showToast('Your slot is held. Continue with your payment provider to confirm.'));

const modal = document.querySelector('#authModal'); const modalTitle = document.querySelector('#modalTitle'); const loginForm = document.querySelector('#loginForm'); const googleRoles = new Set(['Agent', 'Vendor', 'Customer']); let requestedRole = ''; let pendingProductDetails = '';
const googleDivider = document.createElement('div'); googleDivider.className = 'auth-divider'; googleDivider.innerHTML = '<span>OR</span>'; const googleLogin = document.createElement('a'); googleLogin.className = 'google-login'; googleLogin.innerHTML = '<span class="google-mark">G</span> Continue with Google'; loginForm.after(googleDivider, googleLogin);
function openLogin(role = '') { requestedRole = role; modalTitle.textContent = role ? `${role} sign in` : 'Welcome back'; const googleAllowed = googleRoles.has(role); googleLogin.hidden = !googleAllowed; googleDivider.hidden = !googleAllowed; if (googleAllowed) googleLogin.href = `/api/auth/google?role=${encodeURIComponent(role)}`; modal.showModal(); document.querySelector('#email').focus(); }
const signInButton = document.querySelector('#signInButton'); const headerActions = document.querySelector('.header-actions'); const signUpButton = document.createElement('a'); signUpButton.href = 'signup.html'; signUpButton.className = 'button button-outline header-signup'; signUpButton.textContent = 'Create account'; headerActions.insertBefore(signUpButton, signInButton); let signedInAccount = null;
const productAccessDialog = document.createElement('dialog'); productAccessDialog.className = 'product-access-dialog'; productAccessDialog.innerHTML = '<button type="button" class="product-access-close" aria-label="Close">×</button><p class="eyebrow">MEMBERS ONLY</p><h2>Sign in to view this product.</h2><p>Sign in to explore full product details, save items, and continue to purchase or book.</p><div><button type="button" class="button button-dark" data-product-access="signin">Sign in <span>→</span></button><a class="button button-lime" data-product-access="create" href="signup.html">Create account <span>→</span></a></div></dialog>'; document.body.append(productAccessDialog);
function promptProductAccess(url) { pendingProductDetails = url; productAccessDialog.querySelector('[data-product-access="create"]').href = `signup.html?next=${encodeURIComponent(url)}`; productAccessDialog.showModal(); }
productAccessDialog.querySelector('.product-access-close').addEventListener('click', () => productAccessDialog.close()); productAccessDialog.querySelector('[data-product-access="signin"]').addEventListener('click', () => { productAccessDialog.close(); openLogin('Customer'); });
const signInMenu = document.createElement('div'); signInMenu.className = 'signin-menu'; signInMenu.innerHTML = '<span>CHOOSE YOUR WORKSPACE</span><button data-login-role="Customer">Customer</button><button data-login-role="Vendor">Vendor</button><button data-login-role="Agent">Agent</button><hr><button data-login-role="Employee">Employee</button><button data-login-role="Admin">Admin</button>'; headerActions.append(signInMenu);
async function syncSession() { try { const response = await fetch('/api/session', { credentials: 'same-origin' }); const result = await response.json(); if (result.authenticated) { signedInAccount = result.account; signInButton.textContent = 'Sign out'; return; } const requestedProduct = new URLSearchParams(window.location.search).get('product'); if (requestedProduct) promptProductAccess(`product-details.html?product=${encodeURIComponent(requestedProduct)}`); } catch (_) { /* The static preview works without the server. */ } }
signInButton.addEventListener('click', async () => { if (signedInAccount) { await fetch('/api/signout', { method: 'POST', credentials: 'same-origin' }); signedInAccount = null; signInButton.textContent = 'Sign in'; showToast('You have been signed out.'); return; } signInMenu.classList.toggle('open'); }); signInMenu.addEventListener('click', (event) => { const choice = event.target.closest('[data-login-role]'); if (!choice) return; signInMenu.classList.remove('open'); openLogin(choice.dataset.loginRole); }); document.addEventListener('click', (event) => { if (!headerActions.contains(event.target)) signInMenu.classList.remove('open'); }); document.querySelectorAll('.role-login').forEach(button => button.addEventListener('click', () => openLogin(button.dataset.role))); document.querySelector('.close-modal').addEventListener('click', () => modal.close()); syncSession();
document.querySelector('#loginForm').addEventListener('submit', async (event) => { event.preventDefault(); const email = document.querySelector('#email'); const password = document.querySelector('#password'); const error = document.querySelector('#formError'); const submit = event.target.querySelector('[type="submit"]'); error.textContent = ''; if (!email.validity.valid || !password.validity.valid) { error.textContent = 'Enter a valid email and a password of at least 8 characters.'; return; } submit.disabled = true; submit.textContent = 'Signing in…'; try { const response = await fetch('/api/signin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ email: email.value, password: password.value, role: requestedRole }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not sign in.'); modal.close(); event.target.reset(); signedInAccount = result.account; if (pendingProductDetails) { window.location.href = pendingProductDetails; return; } if (result.account.role === 'Admin') { window.location.href = 'admin.html'; return; } if (result.account.role === 'Employee') { window.location.href = 'employee.html'; return; } if (result.account.role === 'Agent') { window.location.href = 'agent.html'; return; } if (result.account.role === 'Vendor') { window.location.href = 'vendor.html'; return; } signInButton.textContent = 'Sign out'; showToast(`Welcome back, ${result.account.firstName}. ${result.account.role} workspace unlocked.`); } catch (requestError) { error.textContent = requestError.message === 'Failed to fetch' ? 'Start the SHAKALPA server before signing in.' : requestError.message; } finally { submit.disabled = false; submit.innerHTML = 'Sign in securely <span>→</span>'; } });
document.querySelector('#trackOrder').addEventListener('click', () => showToast('Demo tracking opened: courier is 12 minutes away.'));
document.querySelector('#driverPin').addEventListener('click', () => showToast('Courier heading to your delivery zone.'));
let mapZoom = 1;
document.querySelector('#zoomIn').addEventListener('click', () => { mapZoom = Math.min(mapZoom + .1, 1.3); document.querySelector('.tracking-map').style.backgroundSize = `${100 * mapZoom}% ${100 * mapZoom}%,${100 * mapZoom}% ${100 * mapZoom}%,18px 18px`; });
document.querySelector('#zoomOut').addEventListener('click', () => { mapZoom = Math.max(mapZoom - .1, .8); document.querySelector('.tracking-map').style.backgroundSize = `${100 * mapZoom}% ${100 * mapZoom}%,${100 * mapZoom}% ${100 * mapZoom}%,18px 18px`; });
