const products = [
  { name: 'Moss ceramic set', type: 'Home / Table', price: 68, tag: 'NEW' },
  { name: 'Arc table light', type: 'Home / Lighting', price: 124, tag: 'BESTSELLER' },
  { name: 'Solace lounge chair', type: 'Home / Furniture', price: 460, tag: '' },
  { name: 'Form side table', type: 'Home / Furniture', price: 220, tag: 'LIMITED' }
];
const cart = [];
const mediaNavigationLink = document.createElement('a');
mediaNavigationLink.href = 'media.html';
mediaNavigationLink.textContent = 'Shagram';
document.querySelector('.site-header nav')?.append(mediaNavigationLink);
const jobsNavigationLink = document.createElement('a');
jobsNavigationLink.href = 'jobs.html';
jobsNavigationLink.textContent = 'Job offers';
document.querySelector('.site-header nav')?.append(jobsNavigationLink);
const productGrid = document.querySelector('#productGrid');
const cartItems = document.querySelector('#cartItems');
const cartCount = document.querySelector('#cartCount');
const cartTotal = document.querySelector('#cartTotal');
const panel = document.querySelector('#cartPanel');
const overlay = document.querySelector('#overlay');
const toast = document.querySelector('#toast');

function escapeHtml(value) {
  const node = document.createElement('span');
  node.textContent = String(value);
  return node.innerHTML;
}
function money(amount, currency = 'USD') { return new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(amount); }
let productQuery = '';
function renderProducts() {
  const matchingProducts = products.map((product, index) => ({ product, index })).filter(({ product }) => `${product.name} ${product.type || ''} ${product.category || ''} ${product.productType || ''} ${product.keywords || ''}`.toLocaleLowerCase().includes(productQuery));
  productGrid.innerHTML = matchingProducts.map(({ product: p, index: i }) => { const media = p.mediaUrl ? (p.mediaUrl.endsWith('.mp4') || p.mediaUrl.endsWith('.webm') ? `<video class="customer-product-media" src="${escapeHtml(p.mediaUrl)}" muted playsinline controls></video>` : `<img class="customer-product-media" src="${escapeHtml(p.mediaUrl)}" alt="${escapeHtml(p.name)}"/>`) : ''; return `<article class="product">${media ? `<div class="product-image has-media">${media}</div>` : '<div class="product-image"></div>'}${p.tag ? `<span class="product-tag">${escapeHtml(p.tag)}</span>` : ''}<button class="add-product" data-index="${i}" aria-label="Add ${escapeHtml(p.name)} to bag">+</button><div class="product-info"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.type)}</small></div><span>${money(p.price, p.currency)}</span></div>${p.specifications ? `<p class="product-specifications">${escapeHtml(p.specifications)}</p>` : ''}</article>`; }).join('') || '<p class="product-search-empty">No products match that search. Try a name, category, type, or keyword.</p>';
}
const baseRenderProducts = renderProducts;
renderProducts = () => { baseRenderProducts(); document.querySelectorAll('#productGrid .product').forEach((card, index) => { const product = products[index]; if (!product?.customerActions) return; const actions = product.customerActions.map((action) => action === 'Buy' ? `<button class="customer-product-action" data-customer-action="buy" data-index="${index}">Buy</button>` : action === 'Book' ? `<button class="customer-product-action" data-customer-action="book" data-index="${index}">Book service</button>` : action === 'Callback' ? `<button class="customer-product-action" data-customer-action="callback" data-index="${index}">Request callback</button>` : `<a class="customer-product-action" href="tel:${escapeHtml(product.vendorPhone || '')}">Call for details</a>`).join(''); card.insertAdjacentHTML('beforeend', `<div class="customer-product-actions">${actions}</div>`); }); };
function renderCart() {
  cartCount.textContent = cart.length;
  if (!cart.length) { cartItems.innerHTML = '<p class="empty-cart">Your bag is ready when you are.</p>'; cartTotal.textContent = '$0.00'; return; }
  cartItems.innerHTML = cart.map((item, index) => `<div class="cart-line"><span>${escapeHtml(item.name)}</span><strong>${money(item.price, item.currency)}</strong><button data-remove="${index}" aria-label="Remove ${escapeHtml(item.name)}">Remove</button></div>`).join('');
  const currencies = new Set(cart.map((item) => item.currency || 'USD'));
  cartTotal.textContent = currencies.size === 1 ? money(cart.reduce((sum, item) => sum + item.price, 0), cart[0].currency) : 'Separate checkout required';
}
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); }
function openCart() { panel.classList.add('open'); overlay.classList.add('visible'); }
function closeCart() { panel.classList.remove('open'); overlay.classList.remove('visible'); }
const productSearch = document.createElement('form'); productSearch.className = 'home-product-search'; productSearch.setAttribute('role', 'search'); productSearch.innerHTML = '<button class="compact-location" type="button" id="useCurrentLocation" aria-label="Use current location" title="Use current location"><span aria-hidden="true">⌖</span><b>Location</b><small id="locationWeather">Select location</small></button><button class="home-search-symbol" type="button" aria-label="Open product search" title="Search products"><span aria-hidden="true"></span></button><label><input id="homeProductSearch" type="search" aria-label="Search products" placeholder="Search by name, category, type, or keyword" autocomplete="off"/></label>';
document.querySelector('.site-header')?.after(productSearch);
productSearch.querySelector('.home-search-symbol').addEventListener('click', () => { productSearch.classList.add('is-open'); document.querySelector('#homeProductSearch').focus(); });
productSearch.addEventListener('submit', (event) => { event.preventDefault(); productQuery = document.querySelector('#homeProductSearch').value.trim().toLocaleLowerCase(); renderProducts(); document.querySelector('#productGrid').scrollIntoView({ behavior: 'smooth', block: 'start' }); });
document.querySelector('#homeProductSearch').addEventListener('input', (event) => { productQuery = event.target.value.trim().toLocaleLowerCase(); renderProducts(); });
document.querySelector('#useCurrentLocation').addEventListener('click', () => { const button = document.querySelector('#useCurrentLocation'); const label = button.querySelector('b'); const weatherLabel = button.querySelector('small'); if (!navigator.geolocation) { label.textContent = 'Unavailable'; return; } label.textContent = 'Locating…'; weatherLabel.textContent = 'Loading weather'; navigator.geolocation.getCurrentPosition(async ({ coords }) => { const latitude = encodeURIComponent(coords.latitude); const longitude = encodeURIComponent(coords.longitude); try { const [placeResponse, weatherResponse] = await Promise.all([fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}&zoom=10`), fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code`)]); const place = await placeResponse.json(); const weather = await weatherResponse.json(); const address = place.address || {}; label.textContent = address.city || address.town || address.village || address.county || 'Current location'; const conditions = { 0: 'Sunny', 1: 'Mostly sunny', 2: 'Partly cloudy', 3: 'Cloudy', 45: 'Foggy', 51: 'Drizzle', 61: 'Rainy', 71: 'Snowy', 80: 'Showers', 95: 'Thunderstorms' }; weatherLabel.textContent = weather.current ? `${Math.round(weather.current.temperature_2m)}°C · ${conditions[weather.current.weather_code] || 'Current weather'}` : 'Weather unavailable'; } catch (_) { label.textContent = 'Current location'; weatherLabel.textContent = 'Weather unavailable'; } }, () => { label.textContent = 'Location'; weatherLabel.textContent = 'Permission needed'; }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); });
const marketTicker = document.createElement('div'); marketTicker.id = 'marketTicker'; marketTicker.className = 'market-ticker'; marketTicker.hidden = true; productSearch.after(marketTicker);
fetch('/api/market-rates', { credentials: 'same-origin' }).then((response) => response.json()).then((rates) => { if (![rates.sensex, rates.gold22k, rates.gold24k, rates.silver].some((value) => value !== '')) return; const format = (value, decimals = 2) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: decimals, minimumFractionDigits: decimals }).format(Number(value)); const pieces = [`SENSEX ${format(rates.sensex, 2)}`, `22K GOLD ₹${format(rates.gold22k)}/g`, `24K GOLD ₹${format(rates.gold24k)}/g`, `SILVER ₹${format(rates.silver)}/g`]; marketTicker.innerHTML = `<div>${[...pieces, ...pieces].map((item) => `<span>${item}</span>`).join('')}</div>`; marketTicker.hidden = false; }).catch(() => {});
renderProducts(); renderCart();
async function loadVendorProductsForCustomers() { const response = await fetch('/api/products', { credentials: 'same-origin' }); const data = await response.json(); if (!response.ok || !Array.isArray(data.products) || !data.products.length) return; const listed = data.products.map((product) => ({ name: product.name, type: [product.category, product.productType, product.vendorName].filter(Boolean).join(' · '), category: product.category || '', productType: product.productType || '', keywords: product.keywords || '', specifications: product.specifications || '', price: product.costPaise / 100, currency: 'INR', tag: 'VENDOR', mediaUrl: product.media?.[0] || '', customerActions: product.customerActions || ['Buy'], vendorPhone: product.vendorPhone || '' })); products.push(...listed); renderProducts(); }
loadVendorProductsForCustomers().catch(() => { /* The public storefront remains available without the API. */ });

productGrid.addEventListener('click', (event) => { const button = event.target.closest('[data-index]'); if (!button) return; const product = products[Number(button.dataset.index)]; if (button.dataset.customerAction === 'book') { showToast(`Booking request started for ${product.name}.`); return; } if (button.dataset.customerAction === 'callback') { const preferred = window.prompt(`Preferred callback date and time for ${product.name} (for example: 20 Sep, 3:30 PM)`); if (preferred?.trim()) showToast(`Callback requested for ${preferred.trim()}. The Vendor will contact you.`); return; } cart.push(product); renderCart(); showToast(`${product.name} added to your bag`); });
cartItems.addEventListener('click', (event) => { const button = event.target.closest('[data-remove]'); if (!button) return; cart.splice(Number(button.dataset.remove), 1); renderCart(); });
document.querySelector('#cartButton').addEventListener('click', openCart); document.querySelector('#closeCart').addEventListener('click', closeCart); overlay.addEventListener('click', closeCart);
document.querySelector('#checkoutButton').addEventListener('click', () => { if (!cart.length) return showToast('Add something to your bag first.'); showToast('Secure checkout would redirect to your payment provider.'); });
document.querySelector('.book-now').addEventListener('click', () => showToast('Your slot is held. Continue with your payment provider to confirm.'));

const modal = document.querySelector('#authModal'); const modalTitle = document.querySelector('#modalTitle'); const loginForm = document.querySelector('#loginForm'); const googleRoles = new Set(['Agent', 'Vendor', 'Customer']); let requestedRole = '';
const googleDivider = document.createElement('div'); googleDivider.className = 'auth-divider'; googleDivider.innerHTML = '<span>OR</span>'; const googleLogin = document.createElement('a'); googleLogin.className = 'google-login'; googleLogin.innerHTML = '<span class="google-mark">G</span> Continue with Google'; loginForm.after(googleDivider, googleLogin);
function openLogin(role = '') { requestedRole = role; modalTitle.textContent = role ? `${role} sign in` : 'Welcome back'; const googleAllowed = googleRoles.has(role); googleLogin.hidden = !googleAllowed; googleDivider.hidden = !googleAllowed; if (googleAllowed) googleLogin.href = `/api/auth/google?role=${encodeURIComponent(role)}`; modal.showModal(); document.querySelector('#email').focus(); }
const signInButton = document.querySelector('#signInButton'); const headerActions = document.querySelector('.header-actions'); const signUpButton = document.createElement('a'); signUpButton.href = 'signup.html'; signUpButton.className = 'button button-outline header-signup'; signUpButton.textContent = 'Create account'; headerActions.insertBefore(signUpButton, signInButton); let signedInAccount = null;
const signInMenu = document.createElement('div'); signInMenu.className = 'signin-menu'; signInMenu.innerHTML = '<span>CHOOSE YOUR WORKSPACE</span><button data-login-role="Customer">Customer</button><button data-login-role="Vendor">Vendor</button><button data-login-role="Agent">Agent</button><hr><button data-login-role="Employee">Employee</button><button data-login-role="Admin">Admin</button>'; headerActions.append(signInMenu);
async function syncSession() { try { const response = await fetch('/api/session', { credentials: 'same-origin' }); const result = await response.json(); if (result.authenticated) { signedInAccount = result.account; signInButton.textContent = 'Sign out'; } } catch (_) { /* The static preview works without the server. */ } }
signInButton.addEventListener('click', async () => { if (signedInAccount) { await fetch('/api/signout', { method: 'POST', credentials: 'same-origin' }); signedInAccount = null; signInButton.textContent = 'Sign in'; showToast('You have been signed out.'); return; } signInMenu.classList.toggle('open'); }); signInMenu.addEventListener('click', (event) => { const choice = event.target.closest('[data-login-role]'); if (!choice) return; signInMenu.classList.remove('open'); openLogin(choice.dataset.loginRole); }); document.addEventListener('click', (event) => { if (!headerActions.contains(event.target)) signInMenu.classList.remove('open'); }); document.querySelectorAll('.role-login').forEach(button => button.addEventListener('click', () => openLogin(button.dataset.role))); document.querySelector('.close-modal').addEventListener('click', () => modal.close()); syncSession();
document.querySelector('#loginForm').addEventListener('submit', async (event) => { event.preventDefault(); const email = document.querySelector('#email'); const password = document.querySelector('#password'); const error = document.querySelector('#formError'); const submit = event.target.querySelector('[type="submit"]'); error.textContent = ''; if (!email.validity.valid || !password.validity.valid) { error.textContent = 'Enter a valid email and a password of at least 8 characters.'; return; } submit.disabled = true; submit.textContent = 'Signing in…'; try { const response = await fetch('/api/signin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ email: email.value, password: password.value, role: requestedRole }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not sign in.'); modal.close(); event.target.reset(); signedInAccount = result.account; if (result.account.role === 'Admin') { window.location.href = 'admin.html'; return; } if (result.account.role === 'Employee') { window.location.href = 'employee.html'; return; } if (result.account.role === 'Agent') { window.location.href = 'agent.html'; return; } if (result.account.role === 'Vendor') { window.location.href = 'vendor.html'; return; } signInButton.textContent = 'Sign out'; showToast(`Welcome back, ${result.account.firstName}. ${result.account.role} workspace unlocked.`); } catch (requestError) { error.textContent = requestError.message === 'Failed to fetch' ? 'Start the SHAKALPA server before signing in.' : requestError.message; } finally { submit.disabled = false; submit.innerHTML = 'Sign in securely <span>→</span>'; } });
document.querySelector('#trackOrder').addEventListener('click', () => showToast('Demo tracking opened: courier is 12 minutes away.'));
document.querySelector('#driverPin').addEventListener('click', () => showToast('Courier heading to your delivery zone.'));
let mapZoom = 1;
document.querySelector('#zoomIn').addEventListener('click', () => { mapZoom = Math.min(mapZoom + .1, 1.3); document.querySelector('.tracking-map').style.backgroundSize = `${100 * mapZoom}% ${100 * mapZoom}%,${100 * mapZoom}% ${100 * mapZoom}%,18px 18px`; });
document.querySelector('#zoomOut').addEventListener('click', () => { mapZoom = Math.max(mapZoom - .1, .8); document.querySelector('.tracking-map').style.backgroundSize = `${100 * mapZoom}% ${100 * mapZoom}%,${100 * mapZoom}% ${100 * mapZoom}%,18px 18px`; });
