(() => {
  const key = 'shakalpa-ride-demo-v1';
  const state = JSON.parse(localStorage.getItem(key) || '{"rides":[],"wallet":0,"payoutVerified":false}');
  const $ = (selector) => document.querySelector(selector);
  const money = (amount) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount);
  const save = () => localStorage.setItem(key, JSON.stringify(state));
  const toast = (message) => { const element = $('#rideToast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 3000); };
  const fare = () => { const type = document.querySelector('input[name="vehicle"]:checked').value; const km = Math.max(0, Number($('#rideDistance').value) || 0); return Math.round((type === 'Cab' ? 40 : 30) + km * (type === 'Cab' ? 16 : 12)); };
  const setEstimate = () => { $('#fareEstimate').textContent = money(fare()); };
  document.querySelectorAll('input[name="vehicle"], #rideDistance').forEach((input) => input.addEventListener('input', setEstimate));
  document.querySelectorAll('input[name="when"]').forEach((input) => input.addEventListener('change', () => { const later = document.querySelector('input[name="when"]:checked').value === 'later'; $('#rideSchedule').hidden = !later; if (later) { const minimum = new Date(Date.now() + 60 * 60 * 1000); $('#rideSchedule').min = minimum.toISOString().slice(0, 16); } }));
  const activeRide = () => state.rides.find((ride) => !['Completed', 'Cancelled'].includes(ride.status));
  const renderCustomer = () => { const ride = activeRide(); const area = $('#activeRide'); area.hidden = !ride; if (!ride) return; const meter = ride.status === 'Meter running' ? money(Math.max(ride.quote || ride.estimate, ride.meterFare || ride.estimate)) : money(ride.quote || ride.estimate); const scheduled = ride.scheduledFor ? new Date(ride.scheduledFor).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : 'Ride now'; area.innerHTML = `<div class="ride-track"><div><p class="eyebrow">ACTIVE RIDE · ${ride.id}</p><div class="ride-status"><i></i>${ride.status}</div><h2>${ride.vehicle} to ${escapeHtml(ride.dropoff)}</h2><div class="ride-meta"><div><span>PICKUP</span><strong>${escapeHtml(ride.pickup)}</strong></div><div><span>TRAVEL</span><strong>${scheduled}</strong></div><div><span>FARE</span><strong>${meter}${ride.quote ? ' · driver quote' : ' · estimate'}</strong></div><div><span>PAYMENT</span><strong>${ride.payment}</strong></div></div><div class="customer-ride-actions"><button class="button button-dark" type="button" id="refreshRide">Refresh status</button><button class="sos-button" type="button" id="rideSos">SOS <span>Emergency help</span></button></div></div><div class="ride-map" aria-label="Vehicle tracking map"><span class="vehicle-dot">${ride.vehicle === 'Cab' ? '🚕' : '🛺'}</span></div></div>`; $('#refreshRide').addEventListener('click', () => { renderAll(); toast('Ride status is up to date.'); }); $('#rideSos').addEventListener('click', openSos); };
  const renderDriver = () => { const requests = state.rides.filter((ride) => ride.status === 'Requested'); const target = $('#driverRequests'); target.innerHTML = requests.length ? requests.map((ride) => `<article class="driver-request"><strong>${ride.vehicle} · ${escapeHtml(ride.pickup)} → ${escapeHtml(ride.dropoff)}</strong><small>${ride.distance} km · estimate ${money(ride.estimate)} · ${ride.scheduledFor ? 'Scheduled' : 'Ride now'}</small><button class="button button-lime" data-accept="${ride.id}" type="button">Accept &amp; quote</button></article>`).join('') : '<p class="empty-state">No ride requests are waiting.</p>';
    target.querySelectorAll('[data-accept]').forEach((button) => button.addEventListener('click', () => { const ride = state.rides.find((entry) => entry.id === button.dataset.accept); const quoteText = prompt('Enter your approximate fare (₹). The customer will see this before the trip starts.', String(ride.estimate)); const quote = Number(quoteText); if (!Number.isFinite(quote) || quote < 1) return toast('Enter a valid fare quote.'); ride.quote = Math.round(quote); ride.status = 'Accepted'; ride.acceptedAt = Date.now(); save(); renderAll(); toast('Ride accepted. The customer can now track the vehicle.'); }));
    const ride = state.rides.find((entry) => ['Accepted', 'Meter running'].includes(entry.status)); const panel = $('#driverActiveRide'); if (!ride) { panel.innerHTML = '<p class="eyebrow">YOUR ACTIVE RIDE</p><p class="empty-state">Accept a ride request to start the meter.</p>'; return; } const currentFare = ride.meterFare || ride.quote || ride.estimate; panel.innerHTML = `<p class="eyebrow">YOUR ACTIVE RIDE · ${ride.id}</p><div class="driver-active"><div><strong>${escapeHtml(ride.pickup)} → ${escapeHtml(ride.dropoff)}</strong><p class="empty-state">Customer payment: ${ride.payment} · Quote: ${money(ride.quote || ride.estimate)}</p></div><div><span class="meter-readout" id="meterReadout">${money(currentFare)}</span><p class="empty-state">${ride.status}</p></div><div>${ride.status === 'Accepted' ? '<button class="button button-lime" id="startMeter" type="button">Start meter</button>' : '<button class="button button-dark" id="completeRide" type="button">Complete ride</button>'}</div></div>`; if (ride.status === 'Accepted') $('#startMeter').addEventListener('click', () => { ride.status = 'Meter running'; ride.meterStartedAt = Date.now(); ride.meterFare = ride.quote || ride.estimate; save(); renderAll(); toast('Meter started. The customer can see live trip status.'); }); if (ride.status === 'Meter running') { $('#completeRide').addEventListener('click', () => { ride.status = 'Completed'; ride.completedAt = Date.now(); ride.finalFare = Math.max(ride.meterFare || 0, ride.quote || ride.estimate); if (ride.payment === 'Shakalpa') state.wallet += ride.finalFare; save(); renderAll(); toast(ride.payment === 'Shakalpa' ? 'Ride completed and fare added to the driver wallet.' : 'Ride completed. Cash was collected outside the wallet.'); }); }
  };
  const renderWallet = () => { $('#walletBalance').textContent = money(state.wallet || 0); $('#payoutStatus').textContent = state.payoutVerified ? 'Verified payout account · immediate payout available.' : 'Verify your payout account before your first immediate payout.'; $('#openPayout').disabled = !(state.wallet > 0); };
  const renderAll = () => { renderCustomer(); renderDriver(); renderWallet(); };
  const escapeHtml = (value) => { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; };
  $('#rideBookingForm').addEventListener('submit', (event) => { event.preventDefault(); const error = $('#bookingError'); error.textContent = ''; if (!event.target.checkValidity()) { error.textContent = 'Complete the pickup, destination, and distance to continue.'; return; } const scheduledFor = document.querySelector('input[name="when"]:checked').value === 'later' ? new Date($('#rideSchedule').value).getTime() : null; if (scheduledFor && (!Number.isFinite(scheduledFor) || scheduledFor < Date.now() + 60 * 60 * 1000)) { error.textContent = 'Scheduled rides must be at least one hour from now.'; return; } const ride = { id: `RIDE-${String(Date.now()).slice(-6)}`, vehicle: document.querySelector('input[name="vehicle"]:checked').value, pickup: $('#ridePickup').value.trim(), dropoff: $('#rideDropoff').value.trim(), distance: Number($('#rideDistance').value), payment: document.querySelector('input[name="payment"]:checked').value, estimate: fare(), scheduledFor, status: 'Requested', createdAt: Date.now() }; state.rides.unshift(ride); save(); event.target.reset(); $('#rideDistance').value = 5; setEstimate(); renderAll(); toast('Ride requested. A driver will accept and share the fare quote.'); });
  document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-mode]').forEach((item) => item.classList.toggle('active', item === button)); document.querySelectorAll('[data-workspace]').forEach((space) => space.hidden = space.dataset.workspace !== button.dataset.mode); }));
  const payoutDialog = $('#payoutDialog'); $('#openPayout').addEventListener('click', () => { if (!(state.wallet > 0)) return; if (state.payoutVerified) { state.wallet = 0; save(); renderAll(); toast('Immediate payout requested. Funds are being sent to your verified account.'); return; } payoutDialog.showModal(); });
  $('#payoutForm').addEventListener('submit', (event) => { event.preventDefault(); const error = $('#payoutError'); error.textContent = ''; if (!event.target.checkValidity()) { error.textContent = 'Enter valid bank account details to verify your payout account.'; return; } state.payoutVerified = true; state.wallet = 0; save(); payoutDialog.close(); renderAll(); toast('Payout account verified and immediate payout requested.'); });
  const sosDialog = $('#sosDialog'); const openSos = () => { const ride = activeRide(); $('#sosDetail').textContent = ride ? `Ride ${ride.id}: ${ride.pickup} to ${ride.dropoff}. We can prepare this information and your current location to share with your emergency contact or responder.` : 'We can prepare your current location to share with emergency support.'; sosDialog.showModal(); }; $('#previewSos').addEventListener('click', openSos); $('#shareSos').addEventListener('click', () => { const ride = activeRide(); const base = `SHAKALPA SOS${ride ? ` · ${ride.id} · ${ride.pickup} to ${ride.dropoff}` : ''}`; if (!navigator.geolocation) { navigator.clipboard?.writeText(base); toast('Ride details copied. Call 112 if you are in danger.'); return; } navigator.geolocation.getCurrentPosition(({ coords }) => { const details = `${base} · Location: https://maps.google.com/?q=${coords.latitude},${coords.longitude}`; if (navigator.share) navigator.share({ title: 'SHAKALPA SOS', text: details }).catch(() => {}); else navigator.clipboard?.writeText(details); toast('Emergency details are ready to share.'); }, () => { navigator.clipboard?.writeText(base); toast('Ride details are ready. Location permission was not granted.'); }, { enableHighAccuracy: true, timeout: 10000 }); });
  document.querySelectorAll('.dialog-close').forEach((button) => button.addEventListener('click', () => button.closest('dialog').close()));
  setEstimate(); renderAll(); setInterval(() => { const ride = activeRide(); if (ride?.status === 'Meter running') { ride.meterFare = Math.round((ride.meterFare || ride.quote || ride.estimate) + 1); save(); renderAll(); } }, 30000);
})();
