(() => {
  const bar = document.querySelector('.home-product-search');
  if (!bar) return;

  const unitSets = {
    length: { label: 'Length', units: { Metre: 1, Kilometre: 1000, Centimetre: .01, Millimetre: .001, Mile: 1609.344, Yard: .9144, Foot: .3048, Inch: .0254 } },
    area: { label: 'Area', units: { 'Square metre': 1, 'Square kilometre': 1e6, Hectare: 10000, Acre: 4046.8564224, 'Square foot': .09290304, 'Square inch': .00064516 } },
    weight: { label: 'Weight', units: { Kilogram: 1, Gram: .001, Milligram: .000001, Tonne: 1000, Pound: .45359237, Ounce: .028349523125 } },
    volume: { label: 'Volume', units: { Litre: 1, Millilitre: .001, 'Cubic metre': 1000, Gallon: 3.785411784, 'US fluid ounce': .0295735295625, Cup: .2365882365 } },
    speed: { label: 'Speed', units: { 'Kilometre/hour': 1, 'Metre/second': 3.6, 'Mile/hour': 1.609344, Knot: 1.852, 'Foot/second': 1.09728 } },
    time: { label: 'Time', units: { Second: 1, Minute: 60, Hour: 3600, Day: 86400, Week: 604800, Month: 2629800, Year: 31557600 } },
    pressure: { label: 'Pressure', units: { Pascal: 1, Kilopascal: 1000, Bar: 100000, PSI: 6894.757293, Atmosphere: 101325, 'mmHg': 133.322387415 } },
    energy: { label: 'Energy', units: { Joule: 1, Kilojoule: 1000, Calorie: 4.184, Kilocalorie: 4184, 'Watt-hour': 3600, 'Kilowatt-hour': 3600000, BTU: 1055.05585262 } },
    power: { label: 'Power', units: { Watt: 1, Kilowatt: 1000, Megawatt: 1e6, Horsepower: 745.699871582 } },
    data: { label: 'Data storage', units: { Byte: 1, Kilobyte: 1000, Megabyte: 1e6, Gigabyte: 1e9, Terabyte: 1e12, Kibibyte: 1024, Mebibyte: 1048576, Gibibyte: 1073741824 } },
    mass: { label: 'Mass', units: { Kilogram: 1, Gram: .001, Tonne: 1000, Pound: .45359237, Ounce: .028349523125 } },
    force: { label: 'Force', units: { Newton: 1, Kilonewton: 1000, 'Pound-force': 4.4482216153, Dyne: .00001 } },
    torque: { label: 'Torque', units: { 'Newton metre': 1, 'Pound-foot': 1.3558179483, 'Pound-inch': .112984829 } },
    density: { label: 'Density', units: { 'Kilogram/cubic metre': 1, 'Gram/cubic centimetre': 1000, 'Pound/cubic foot': 16.01846337 } },
    angle: { label: 'Angle', units: { Degree: 1, Radian: 57.2957795131, Gradian: .9, Arcminute: .0166666667, Arcsecond: .0002777778 } },
    frequency: { label: 'Frequency', units: { Hertz: 1, Kilohertz: 1000, Megahertz: 1e6, Gigahertz: 1e9, RPM: .0166666667 } },
    electrical: { label: 'Electrical voltage', units: { Volt: 1, Millivolt: .001, Kilovolt: 1000, Microvolt: .000001 } }
  };
  const tools = {
    units: ['length','area','weight','volume','temperature','speed','time','pressure','energy','power','data','fuel'],
    finance: ['currency','gst','percentage','emi','interest','salary','discount','profit'],
    engineering: ['length','mass','force','torque','pressure','density','angle','frequency','electrical','power','energy'],
    everyday: ['age','date','timezone','cooking','shoe','words','roman']
  };
  const labels = { temperature:'Temperature', fuel:'Fuel consumption', currency:'Currency converter', gst:'GST calculator', percentage:'Percentage calculator', emi:'EMI / loan calculator', interest:'Interest calculator', salary:'Salary converter', discount:'Discount calculator', profit:'Profit-margin calculator', age:'Age calculator', date:'Date difference', timezone:'Time-zone converter', cooking:'Cooking measurements', shoe:'Shoe / clothing sizes', words:'Number to words', roman:'Roman numerals' };
  const liveCurrencyRates = new Map();
  const dialog = document.createElement('dialog');
  dialog.className = 'converter-dialog';
  dialog.innerHTML = '<button type="button" class="converter-close" aria-label="Close converters">×</button><p class="eyebrow">SHAKALPA TOOLS</p><h2>Converters</h2><p class="converter-copy">Enter a value and see the result instantly.</p><div class="converter-selects"><label>Category<select id="converterGroup"><option value="units">Unit converters</option><option value="finance">Finance converters</option><option value="engineering">Measurement & engineering</option><option value="everyday">Everyday converters</option></select></label><label>Converter<select id="converterTool"></select></label></div><form id="converterForm" novalidate><div id="converterFields"></div></form><output id="converterResult" class="converter-result" aria-live="polite"></output>';
  document.body.append(dialog);
  const group = dialog.querySelector('#converterGroup'), tool = dialog.querySelector('#converterTool'), fields = dialog.querySelector('#converterFields'), result = dialog.querySelector('#converterResult');
  const options = (items, selected) => Object.keys(items).map(key => `<option value="${key}"${key === selected ? ' selected' : ''}>${key}</option>`).join('');
  const number = (id, label, value = '') => `<label>${label}<input id="${id}" type="number" step="any" value="${value}" inputmode="decimal" required/></label>`;
  const select = (id, label, values, chosen) => `<label>${label}<select id="${id}">${options(values, chosen)}</select></label>`;
  const format = value => Number.isFinite(value) ? new Intl.NumberFormat('en-IN',{maximumFractionDigits:8}).format(value) : 'Enter valid values';
  function linear(name) { const set = unitSets[name]; fields.innerHTML = `${number('converterValue','Value','1')}${select('converterFrom','From',set.units,Object.keys(set.units)[0])}${select('converterTo','To',set.units,Object.keys(set.units)[1] || Object.keys(set.units)[0])}`; return () => { const value = Number(fields.querySelector('#converterValue').value), from = fields.querySelector('#converterFrom').value, to = fields.querySelector('#converterTo').value; result.textContent = `${format(value * set.units[from] / set.units[to])} ${to}`; }; }
  function temperature() { const units = { Celsius:1, Fahrenheit:1, Kelvin:1 }; fields.innerHTML = `${number('converterValue','Temperature','25')}${select('converterFrom','From',units,'Celsius')}${select('converterTo','To',units,'Fahrenheit')}`; return () => { const v=Number(fields.querySelector('#converterValue').value), from=fields.querySelector('#converterFrom').value, to=fields.querySelector('#converterTo').value; const c=from==='Celsius'?v:from==='Fahrenheit'?(v-32)*5/9:v-273.15; const out=to==='Celsius'?c:to==='Fahrenheit'?c*9/5+32:c+273.15; result.textContent=`${format(out)} °${to === 'Kelvin' ? 'K' : to[0]}`; }; }
  function fuel() { const units={'Kilometre/litre':1,'Litre/100 km':1,'US miles/gallon':1,'UK miles/gallon':1}; fields.innerHTML=`${number('converterValue','Fuel consumption','15')}${select('converterFrom','From',units,'Kilometre/litre')}${select('converterTo','To',units,'Litre/100 km')}`; return () => { const v=Number(fields.querySelector('#converterValue').value), from=fields.querySelector('#converterFrom').value,to=fields.querySelector('#converterTo').value; if(!(v>0)) return result.textContent='Enter a value greater than zero'; const l100=from==='Kilometre/litre'?100/v:from==='Litre/100 km'?v:from==='US miles/gallon'?235.214583/v:282.481/v; const out=to==='Kilometre/litre'?100/l100:to==='Litre/100 km'?l100:to==='US miles/gallon'?235.214583/l100:282.481/l100; result.textContent=`${format(out)} ${to}`; }; }
  function finance(name) {
    if(name==='currency'){const currencies={INR:1,USD:1,EUR:1,GBP:1,AED:1,SGD:1,JPY:1};fields.innerHTML=`${number('converterValue','Amount','1')}${select('converterFrom','From',currencies,'INR')}${select('converterTo','To',currencies,'USD')}<small class="converter-note">Latest available daily reference rate · <a href="https://www.exchangerate-api.com" target="_blank" rel="noopener noreferrer">Rates by ExchangeRate-API</a> · Not a payment quote.</small>`;let requestId=0;return async()=>{const v=Number(fields.querySelector('#converterValue').value),f=fields.querySelector('#converterFrom').value,t=fields.querySelector('#converterTo').value;if(!Number.isFinite(v))return result.textContent='Enter a valid amount';const key=`${f}-${t}`,current=++requestId;result.textContent='Fetching current exchange rate…';try{let rate=liveCurrencyRates.get(key);if(!rate){const response=await fetch(`/api/currency-rate?from=${encodeURIComponent(f)}&to=${encodeURIComponent(t)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Live rates are unavailable.');rate=data;liveCurrencyRates.set(key,rate);}if(current!==requestId)return;result.textContent=`${format(v*rate.rate)} ${t} · 1 ${f} = ${format(rate.rate)} ${t} · ${rate.date}`;}catch(error){if(current===requestId)result.textContent=error.message;}};}
    if(name==='gst'){fields.innerHTML=`${number('a','Amount excluding GST','1000')}${number('b','GST rate (%)','18')}`;return()=>{const a=Number(fields.querySelector('#a').value),b=Number(fields.querySelector('#b').value)/100,g=a*b;result.textContent=`GST: ₹${format(g)} · Total: ₹${format(a+g)}`;};}
    if(name==='percentage'){fields.innerHTML=`${number('a','Value','25')}${number('b','Total','100')}`;return()=>{const a=Number(fields.querySelector('#a').value),b=Number(fields.querySelector('#b').value);result.textContent=b?`${format(a/b*100)}%`:'Enter a total greater than zero';};}
    if(name==='emi'){fields.innerHTML=`${number('a','Loan amount (₹)','500000')}${number('b','Annual interest (%)','9')}${number('c','Term (months)','60')}`;return()=>{const p=Number(fields.querySelector('#a').value),r=Number(fields.querySelector('#b').value)/1200,n=Number(fields.querySelector('#c').value),emi=r?p*r*(1+r)**n/((1+r)**n-1):p/n;result.textContent=`Monthly EMI: ₹${format(emi)} · Total: ₹${format(emi*n)}`;};}
    if(name==='interest'){fields.innerHTML=`${number('a','Principal (₹)','100000')}${number('b','Annual interest (%)','7')}${number('c','Years','2')}`;return()=>{const p=Number(fields.querySelector('#a').value),r=Number(fields.querySelector('#b').value)/100,y=Number(fields.querySelector('#c').value),i=p*r*y;result.textContent=`Simple interest: ₹${format(i)} · Total: ₹${format(p+i)}`;};}
    if(name==='salary'){fields.innerHTML=number('a','Annual salary (₹)','600000');return()=>{const a=Number(fields.querySelector('#a').value);result.textContent=`Monthly: ₹${format(a/12)} · Weekly: ₹${format(a/52)} · Daily: ₹${format(a/260)}`;};}
    if(name==='discount'){fields.innerHTML=`${number('a','Original price (₹)','1000')}${number('b','Discount (%)','20')}`;return()=>{const a=Number(fields.querySelector('#a').value),b=Number(fields.querySelector('#b').value)/100;result.textContent=`You save ₹${format(a*b)} · Final price: ₹${format(a*(1-b))}`;};}
    fields.innerHTML=`${number('a','Cost price (₹)','800')}${number('b','Selling price (₹)','1000')}`;return()=>{const c=Number(fields.querySelector('#a').value),s=Number(fields.querySelector('#b').value),p=s-c;result.textContent=s?`Profit: ₹${format(p)} · Margin: ${format(p/s*100)}%`:'Enter a selling price';};
  }
  function everyday(name) {
    if(name==='age'){fields.innerHTML='<label>Date of birth<input id="a" type="date" required/></label>';return()=>{const d=new Date(fields.querySelector('#a').value),now=new Date();if(Number.isNaN(d))return result.textContent='Select your date of birth';let y=now.getFullYear()-d.getFullYear(),m=now.getMonth()-d.getMonth(),day=now.getDate()-d.getDate();if(day<0){m--;day+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}result.textContent=`${y} years, ${m} months and ${day} days`;};}
    if(name==='date'){fields.innerHTML='<label>Start date<input id="a" type="date" required/></label><label>End date<input id="b" type="date" required/></label>';return()=>{const a=new Date(fields.querySelector('#a').value),b=new Date(fields.querySelector('#b').value),days=Math.round((b-a)/86400000);result.textContent=Number.isFinite(days)?`${Math.abs(days)} days (${format(Math.abs(days)/7)} weeks)`:'Select both dates';};}
    if(name==='timezone'){const zones={'Asia/Kolkata':'India (IST)','UTC':'UTC','Europe/London':'London','America/New_York':'New York','America/Los_Angeles':'Los Angeles','Asia/Dubai':'Dubai','Asia/Singapore':'Singapore','Australia/Sydney':'Sydney'};fields.innerHTML='<label>UTC date and time<input id="a" type="datetime-local" required/></label>'+select('b','Destination time zone',zones,'Asia/Kolkata');return()=>{const v=fields.querySelector('#a').value,z=fields.querySelector('#b').value;if(!v)return result.textContent='Select a UTC date and time';const d=new Date(`${v}Z`);result.textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'full',timeStyle:'short',timeZone:z}).format(d);};}
    if(name==='cooking'){const units={Millilitre:1,Teaspoon:4.92892,Tablespoon:14.7868,Cup:236.588,Litre:1000,'US fluid ounce':29.5735};fields.innerHTML=`${number('converterValue','Amount','1')}${select('converterFrom','From',units,'Cup')}${select('converterTo','To',units,'Millilitre')}`;return()=>{const v=Number(fields.querySelector('#converterValue').value),f=fields.querySelector('#converterFrom').value,t=fields.querySelector('#converterTo').value;result.textContent=`${format(v*units[f]/units[t])} ${t}`;};}
    if(name==='shoe'){const systems={'India / UK':1,'US men':1,'US women':1,'EU':1};fields.innerHTML=`${number('a','Shoe size','7')}${select('b','From',systems,'India / UK')}${select('c','To',systems,'EU')}<small class="converter-note">Approximate adult-size guide; brand fit can vary.</small>`;return()=>{const s=Number(fields.querySelector('#a').value),f=fields.querySelector('#b').value,t=fields.querySelector('#c').value;let uk=f==='EU'?s-33:f==='US men'?s-1:f==='US women'?s-2:s;let out=t==='EU'?uk+33:t==='US men'?uk+1:t==='US women'?uk+2:uk;result.textContent=`Approximate ${t} size: ${format(out)}`;};}
    if(name==='words'){fields.innerHTML=number('a','Number (up to 999,999,999,999)','12345');return()=>{const n=Math.floor(Number(fields.querySelector('#a').value));result.textContent=numberWords(n)||'Enter a whole number in the supported range';};}
    fields.innerHTML=number('a','Number (1–3999)','2026');return()=>{const n=Math.floor(Number(fields.querySelector('#a').value));result.textContent=n>0&&n<4000?roman(n):'Enter a whole number from 1 to 3999';};
  }
  function numberWords(n){if(!Number.isFinite(n)||n<0||n>999999999999)return '';const small=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'],tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];const chunk=x=>x<20?small[x]:x<100?`${tens[Math.floor(x/10)]}${x%10?' '+small[x%10]:''}`:`${small[Math.floor(x/100)]} hundred${x%100?' '+chunk(x%100):''}`;if(n<1000)return chunk(n);const parts=[];[['billion',1e9],['million',1e6],['thousand',1000]].forEach(([word,value])=>{if(n>=value){parts.push(`${chunk(Math.floor(n/value))} ${word}`);n%=value}});if(n)parts.push(chunk(n));return parts.join(' ');}
  function roman(n){const map=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];return map.map(([v,s])=>{const x=Math.floor(n/v);n%=v;return s.repeat(x)}).join('');}
  function renderTools(){const collection=tools[group.value];tool.innerHTML=collection.map(id=>`<option value="${id}">${unitSets[id]?.label||labels[id]}</option>`).join('');renderFields();}
  function renderFields(){let update;const id=tool.value;if(unitSets[id])update=linear(id);else if(id==='temperature')update=temperature();else if(id==='fuel')update=fuel();else if(group.value==='finance')update=finance(id);else update=everyday(id);fields.oninput=update;fields.onchange=update;update();}
  group.addEventListener('change',renderTools);tool.addEventListener('change',renderFields);dialog.querySelector('.converter-close').addEventListener('click',()=>dialog.close());renderTools();
  const button=document.createElement('button');button.type='button';button.className='converter-symbol';button.setAttribute('aria-label','Open converters');button.title='Converters';button.innerHTML='<span aria-hidden="true">∑</span>';button.addEventListener('click',()=>dialog.showModal());bar.prepend(button);
})();
