const toast = document.querySelector('#toast'); const applyDialog = document.querySelector('#applyDialog'); let jobs = []; let viewer = null; let selectedJobId = null;
function escapeHtml(value) { const node = document.createElement('span'); node.textContent = String(value); return node.innerHTML; }
function toastMessage(message) { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2800); }
function renderJobs() { const target = document.querySelector('#jobOfferRows'); target.innerHTML = jobs.map((job) => `<article class="job-offer"><div class="job-offer-top"><div><p class="eyebrow">${escapeHtml(job.businessName)}</p><h2>${escapeHtml(job.title)}</h2></div><span>${escapeHtml(job.employmentType)}</span></div><p class="job-meta">${escapeHtml(job.location)}${job.salaryDetails ? ` · ${escapeHtml(job.salaryDetails)}` : ''}</p><p class="job-description">${escapeHtml(job.description)}</p><div class="job-actions"><button type="button" data-share="${job.id}">Share</button><button type="button" data-refer="${job.id}">Refer a friend</button><button type="button" class="job-apply" data-apply="${job.id}" ${job.applied ? 'disabled' : ''}>${job.applied ? 'Applied' : 'Apply now'} <span>→</span></button></div></article>`).join('') || '<p class="empty-jobs">No job offers are available right now.</p>'; }
async function loadJobs() { const response = await fetch('/api/jobs', { credentials: 'same-origin' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load job offers.'); jobs = data.jobs || []; viewer = data.viewer; document.querySelector('#jobsSignin').hidden = Boolean(viewer?.role === 'Customer'); renderJobs(); }
function shareJob(job, referral) { const text = `${referral ? 'I think you would be great for' : 'Take a look at'} ${job.title} at ${job.businessName} on SHAKALPA.`; const share = { title: `${job.title} · SHAKALPA`, text, url: window.location.href }; if (navigator.share) navigator.share(share).catch(() => {}); else navigator.clipboard.writeText(`${text} ${window.location.href}`).then(() => toastMessage('Job link copied to share.')).catch(() => toastMessage('Copy this page link to share the opening.')); }
document.querySelector('#jobOfferRows').addEventListener('click', (event) => { const button = event.target.closest('[data-share],[data-refer],[data-apply]'); if (!button) return; const job = jobs.find((item) => item.id === Number(button.dataset.share || button.dataset.refer || button.dataset.apply)); if (!job) return; if (button.dataset.share) { shareJob(job, false); return; } if (button.dataset.refer) { shareJob(job, true); return; } if (!viewer || viewer.role !== 'Customer') { document.querySelector('#jobsSignin').hidden = false; document.querySelector('#jobsSignin').scrollIntoView({ behavior: 'smooth', block: 'center' }); return; } selectedJobId = job.id; document.querySelector('#applyJobTitle').textContent = `Apply for ${job.title}`; document.querySelector('#applyError').textContent = ''; applyDialog.showModal(); });
document.querySelector('.close-job-dialog').addEventListener('click', () => applyDialog.close());
document.querySelector('#applyJobForm').addEventListener('submit', async (event) => { event.preventDefault(); const error = document.querySelector('#applyError'); error.textContent = ''; try { const response = await fetch('/api/jobs/apply', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ jobId: selectedJobId, coverNote: document.querySelector('#applyCoverNote').value }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not send application.'); applyDialog.close(); event.target.reset(); toastMessage(data.message); await loadJobs(); } catch (requestError) { error.textContent = requestError.message; } });
document.querySelector('#refreshJobs').addEventListener('click', () => loadJobs().catch((error) => toastMessage(error.message))); loadJobs().catch((error) => { document.querySelector('#jobOfferRows').textContent = error.message; });
