(() => {
  const bar = document.querySelector('.home-product-search'); if (!bar) return;
  const plans = (provider, values) => ({ provider, plans: values });
  const services = {
    fasttag: ['FASTag recharge','Vehicle number','TN 01 AB 1234',[plans('HDFC FASTag',[['Top-up ₹200',200],['Top-up ₹500',500],['Top-up ₹1,000',1000]]),plans('ICICI FASTag',[['Top-up ₹200',200],['Top-up ₹500',500],['Top-up ₹1,000',1000]]),plans('SBI FASTag',[['Top-up ₹200',200],['Top-up ₹500',500],['Top-up ₹1,000',1000]])]],
    prepaid: ['Mobile prepaid','Mobile number','10-digit mobile number',[plans('Airtel',[['₹149 · talktime',149],['₹249 · 28 days',249],['₹719 · 84 days',719],['₹2,999 · annual',2999]]),plans('Jio',[['₹189 · 28 days',189],['₹299 · 28 days',299],['₹666 · 84 days',666],['₹3,599 · annual',3599]]),plans('Vi',[['₹199 · 28 days',199],['₹299 · 28 days',299],['₹719 · 84 days',719],['₹3,199 · annual',3199]]),plans('BSNL',[['₹107 · 35 days',107],['₹199 · 30 days',199],['₹599 · 84 days',599],['₹1,999 · annual',1999]])]],
    postpaid: ['Mobile postpaid','Mobile number','10-digit mobile number',[plans('Airtel',[['₹399 · monthly',399],['₹499 · monthly',499],['₹799 · monthly',799]]),plans('Jio',[['₹399 · monthly',399],['₹599 · monthly',599],['₹899 · monthly',899]]),plans('Vi',[['₹401 · monthly',401],['₹501 · monthly',501],['₹701 · monthly',701]]),plans('BSNL',[['₹199 · monthly',199],['₹399 · monthly',399],['₹599 · monthly',599]])]],
    dth: ['DTH recharge','Subscriber ID','Enter subscriber ID',[plans('Tata Play',[['Family pack ₹299',299],['Sports pack ₹499',499],['Premium pack ₹799',799]]),plans('Airtel Digital TV',[['Family pack ₹300',300],['Sports pack ₹500',500],['Premium pack ₹800',800]]),plans('Dish TV',[['Family pack ₹280',280],['Sports pack ₹480',480],['Premium pack ₹780',780]]),plans('d2h',[['Family pack ₹290',290],['Sports pack ₹490',490],['Premium pack ₹790',790]]),plans('Sun Direct',[['Family pack ₹250',250],['Sports pack ₹450',450],['Premium pack ₹700',700]])]],
    broadband: ['Broadband recharge','Customer ID','Enter customer ID',[plans('JioFiber',[['Basic ₹399',399],['Unlimited ₹699',699],['High-speed ₹999',999]]),plans('Airtel Xstream',[['Basic ₹499',499],['Unlimited ₹799',799],['High-speed ₹1,199',1199]]),plans('BSNL Bharat Fiber',[['Basic ₹499',499],['Unlimited ₹799',799],['High-speed ₹999',999]]),plans('ACT Fibernet',[['Basic ₹599',599],['Unlimited ₹899',899],['High-speed ₹1,299',1299]])]],
    landline: ['Landline bill','Landline number','STD code and number',[plans('BSNL',[['₹299 monthly bill',299],['₹399 monthly bill',399],['₹599 monthly bill',599]]),plans('Airtel',[['₹299 monthly bill',299],['₹499 monthly bill',499],['₹699 monthly bill',699]])]],
    cable: ['Cable TV recharge','Customer ID','Enter customer ID',[plans('Hathway',[['Starter ₹250',250],['Family ₹350',350],['Entertainment ₹500',500]]),plans('DEN',[['Starter ₹250',250],['Family ₹350',350],['Entertainment ₹500',500]]),plans('Siti Cable',[['Starter ₹240',240],['Family ₹340',340],['Entertainment ₹490',490]])]],
    metro: ['Metro recharge','Metro card number','Enter card number',[plans('Delhi Metro',[['Quick top-up ₹100',100],['Commute ₹300',300],['Monthly credit ₹1,000',1000]]),plans('Chennai Metro',[['Quick top-up ₹100',100],['Commute ₹300',300],['Monthly credit ₹1,000',1000]]),plans('Bengaluru Metro',[['Quick top-up ₹100',100],['Commute ₹300',300],['Monthly credit ₹1,000',1000]])]],
    ncmc: ['NCMC recharge','NCMC card number','Enter card number',[plans('RuPay NCMC',[['Quick top-up ₹100',100],['Travel ₹300',300],['Monthly credit ₹1,000',1000]]),plans('SBI NCMC',[['Quick top-up ₹100',100],['Travel ₹300',300],['Monthly credit ₹1,000',1000]])]]
  };
  const dialog=document.createElement('dialog');dialog.className='recharge-dialog';dialog.innerHTML='<button type="button" class="recharge-close" aria-label="Close recharge">×</button><p class="eyebrow">SHAKALPA PAY</p><h2>Recharge &amp; bills</h2><p class="recharge-copy">Choose a service, provider, and plan before payment.</p><div class="recharge-services"></div><form id="rechargeForm" novalidate><label id="rechargeAccountLabel">Account<input id="rechargeAccount" required maxlength="80"/></label><label>Provider<select id="rechargeProvider" required></select></label><label>Plan<select id="rechargePlan" required></select></label><label>Plan amount <span class="required-marker">*</span><input id="rechargeAmount" type="number" min="10" max="100000" required readonly/></label><fieldset><legend>Pay with</legend><label><input type="radio" name="rechargePayment" value="Wallet" checked/> Shakalpa Wallet</label><label><input type="radio" name="rechargePayment" value="Other payment method"/> Other payment method</label></fieldset><p class="recharge-note">Your recharge request is saved securely. Its payment status is sent to your registered email and phone.</p><p id="rechargeError" class="form-error" role="alert"></p><button class="button button-lime full" type="submit">Continue to pay <span>→</span></button></form>';document.body.append(dialog);
  const grid=dialog.querySelector('.recharge-services'),accountLabel=dialog.querySelector('#rechargeAccountLabel'),account=dialog.querySelector('#rechargeAccount'),provider=dialog.querySelector('#rechargeProvider'),plan=dialog.querySelector('#rechargePlan'),amount=dialog.querySelector('#rechargeAmount');let serviceId='fasttag';const esc=value=>{const n=document.createElement('span');n.textContent=value;return n.innerHTML};const toast=message=>{const n=document.querySelector('#toast');if(!n)return;n.textContent=message;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),3500)};
  const setPlans=()=>{const packs=services[serviceId][3],selected=packs[provider.selectedIndex]||packs[0];plan.innerHTML=selected.plans.map(([name,value],index)=>`<option value="${index}">${esc(name)} · ₹${value.toLocaleString('en-IN')}</option>`).join('');amount.value=selected.plans[0][1]};const render=()=>{const [label,accountName,placeholder,packs]=services[serviceId];grid.innerHTML=Object.entries(services).map(([id,service])=>`<button type="button" class="${id===serviceId?'selected':''}" data-service="${id}">${esc(service[0])}</button>`).join('');accountLabel.firstChild.textContent=accountName;account.placeholder=placeholder;provider.innerHTML=packs.map((pack,index)=>`<option value="${index}">${esc(pack.provider)}</option>`).join('');setPlans();grid.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>{serviceId=button.dataset.service;render()}));};render();provider.addEventListener('change',setPlans);plan.addEventListener('change',()=>{const selected=services[serviceId][3][provider.selectedIndex].plans[plan.selectedIndex];amount.value=selected[1]});dialog.querySelector('.recharge-close').addEventListener('click',()=>dialog.close());
  dialog.querySelector('#rechargeForm').addEventListener('submit',async event=>{event.preventDefault();const error=dialog.querySelector('#rechargeError');error.textContent='';if(!event.target.checkValidity()){error.textContent='Enter a valid account reference.';return}const [serviceName,,,packs]=services[serviceId],pack=packs[provider.selectedIndex],selected=pack.plans[plan.selectedIndex],paymentMethod=dialog.querySelector('input[name="rechargePayment"]:checked').value,submit=event.target.querySelector('[type="submit"]');submit.disabled=true;try{const response=await fetch('/api/recharges',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({serviceType:serviceName,accountReference:account.value.trim(),planName:`${pack.provider} · ${selected[0]}`,amountPaise:Math.round(selected[1]*100),paymentMethod})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not create the recharge payment request.');dialog.close();const channels=[data.emailSent&&'email',data.smsSent&&'SMS'].filter(Boolean);toast(`${data.message}${channels.length?` Notification sent by ${channels.join(' and ')}.`:' Notifications will send when email/SMS is configured.'}`)}catch(requestError){error.textContent=requestError.message==='Sign in as a Customer before making a recharge payment.'?'Please sign in with your Customer account to continue.':requestError.message}finally{submit.disabled=false}});
  const detailBox=document.createElement('section');detailBox.className='recharge-plan-details';grid.after(detailBox);const updatePlanDetails=()=>{const [serviceName,,,packs]=services[serviceId],pack=packs[provider.selectedIndex],selected=pack.plans[plan.selectedIndex];let detail='Recharge value is applied to this account after successful operator confirmation.';if(serviceId==='prepaid'){const value=selected[1],duration=value>=1900?'365 days':value>=599?'84 days':'28 days',data=value>=1900?'2 GB/day':value>=599?'1.5 GB/day':value>=249?'1 GB/day':'Talktime only',sms=value>=249?'100 SMS/day':'SMS charges as per provider';detail=`Validity: ${duration} · Data: ${data} · Calls: unlimited where included · SMS: ${sms}`;}else if(serviceId==='postpaid'){detail='Monthly bill plan · Talktime, data allowance, SMS limit, and roaming benefits are confirmed by the provider at payment.';}else if(serviceId==='dth'||serviceId==='cable'){detail='Package channels and add-ons are confirmed by the provider before final payment.';}else if(serviceId==='broadband'){detail='Monthly broadband plan · Speed, data/FUP, and validity are confirmed by the provider before final payment.';}detailBox.innerHTML=`<strong>${esc(pack.provider)} · ${esc(selected[0])}</strong><p>${esc(detail)}</p><small>Plan details are from the local catalogue. Live provider data is required for the current complete plan list and final benefits.</small>`;};updatePlanDetails();provider.addEventListener('change',updatePlanDetails);plan.addEventListener('change',updatePlanDetails);
  const button=document.createElement('button');button.type='button';button.className='recharge-symbol';button.setAttribute('aria-label','Open recharge and bills');button.title='Recharge & bills';button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="2.75" width="12" height="18.5" rx="2.5"/><path d="M10 6h4M11.3 9.2 9.5 13h2l-.5 2.2 3.5-4.8h-2l.5-1.2"/><path d="M10.5 18h3"/></svg>';button.addEventListener('click',()=>dialog.showModal());const calculator=bar.querySelector('.calculator-symbol');if(calculator)calculator.insertAdjacentElement('beforebegin',button);else bar.prepend(button);
})();
