(() => {
  const bar = document.querySelector('.home-product-search');
  if (!bar || document.querySelector('.tracking-symbol')) return;
  const dialog = document.createElement('dialog');
  dialog.className = 'tracking-dialog';
  dialog.innerHTML = `<button type="button" class="tracking-close" aria-label="Close train live tracking">×</button><p class="eyebrow">RAIL JOURNEY</p><h2>Live train tracking</h2><p class="tracking-copy">Track a train’s current running position, next station, and estimated arrival.</p><form id="trainTrackingForm" novalidate><label>Train number <span class="required-marker">*</span><input id="trainNumber" inputmode="numeric" pattern="[0-9]{5}" maxlength="5" placeholder="For example, 12627" required/></label><label>Journey date <span class="required-marker">*</span><input id="trainJourneyDate" type="date" required/></label><button class="button button-lime" type="submit">Track train <span>→</span></button></form><section class="tracking-status" id="trackingStatus" aria-live="polite" hidden><span class="tracking-pulse" aria-hidden="true"></span><div><strong id="trackingState">Looking up train…</strong><small id="trackingUpdated"></small></div></section><section class="train-tracking-result" id="trainTrackingResult" hidden></section><p class="form-error" id="trackingError" role="alert"></p><p class="tracking-note">Live railway movement is available only after an authorised rail-status provider is connected. The tracker will not guess a train’s position.</p>`;
  document.body.append(dialog);
  const date = dialog.querySelector('#trainJourneyDate'); date.value = new Date().toISOString().slice(0, 10);
  const form = dialog.querySelector('#trainTrackingForm'), status = dialog.querySelector('#trackingStatus'), state = dialog.querySelector('#trackingState'), updated = dialog.querySelector('#trackingUpdated'), result = dialog.querySelector('#trainTrackingResult'), error = dialog.querySelector('#trackingError');
  const esc = value => { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; };
  const renderTrain = data => { result.hidden = false; result.innerHTML = `<div class="train-result-head"><div><span>TRAIN ${esc(data.trainNumber)}</span><strong>${esc(data.trainName || 'Live journey')}</strong></div><b class="train-running">${esc(data.status || 'Running')}</b></div><div class="train-progress"><i style="width:${Math.max(3, Math.min(100, Number(data.progress) || 0))}%"></i></div><div class="train-route"><div><small>Last reported</small><strong>${esc(data.lastStation || '—')}</strong><span>${esc(data.lastTime || 'Awaiting update')}</span></div><div><small>Next station</small><strong>${esc(data.nextStation || '—')}</strong><span>${esc(data.nextArrival || 'Awaiting update')}</span></div></div><div class="train-boarding"><div><span class="boarding-icon" aria-hidden="true">▤</span><div><small>Coach position</small><strong>${esc(data.coachPosition || 'Confirm at station')}</strong><span>${esc(data.coachNote || 'Coach order is published after it is received from the rail provider.')}</span></div></div><div><span class="boarding-icon" aria-hidden="true">⌖</span><div><small>Platform</small><strong>${esc(data.platform || 'Awaiting announcement')}</strong><span>${esc(data.platformNote || 'Platform can change; check the final station display and announcement.')}</span></div></div></div>`; };
  form.addEventListener('submit', async event => { event.preventDefault(); error.textContent = ''; result.hidden = true; if (!form.checkValidity()) { error.textContent = 'Enter a valid 5-digit train number and journey date.'; return; } const submit = form.querySelector('[type="submit"]'); submit.disabled = true; status.hidden = false; status.classList.remove('is-live'); state.textContent = 'Checking live train status…'; updated.textContent = 'This can take a few seconds.'; try { const response = await fetch(`/api/train-tracking?trainNumber=${encodeURIComponent(dialog.querySelector('#trainNumber').value)}&journeyDate=${encodeURIComponent(date.value)}`, { credentials: 'same-origin' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Live train tracking is unavailable.'); state.textContent = 'Live train status'; updated.textContent = `Updated ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`; status.classList.add('is-live'); renderTrain(data); } catch (requestError) { state.textContent = 'Live data connection needed'; updated.textContent = 'No live train provider is connected yet.'; error.textContent = requestError.message.includes('provider') ? requestError.message : 'Connect an authorised rail-status provider to show live train positions.'; } finally { submit.disabled = false; } });
  dialog.querySelector('.tracking-close').addEventListener('click', () => dialog.close());
  const button = document.createElement('button'); button.type = 'button'; button.className = 'tracking-symbol'; button.setAttribute('aria-label', 'Open live train tracking'); button.title = 'Live train tracking'; button.innerHTML = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3.5h10a2 2 0 0 1 2 2v10.2a4.2 4.2 0 0 1-4.2 4.2H9.2A4.2 4.2 0 0 1 5 15.7V5.5a2 2 0 0 1 2-2Z"/><path d="M8.5 7.5h7M9 12h1M14 12h1M8 20.2 6.4 22M16 20.2l1.6 1"/><path d="M9 16h6"/></svg>'; button.addEventListener('click', () => dialog.showModal()); const calculator = bar.querySelector('.calculator-symbol'); if (calculator) calculator.insertAdjacentElement('beforebegin', button); else bar.append(button);
})();
